name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: I have checked the documentation to see if this feature already exists
          required: true
        - label: This feature request is related to the ASUS ROG Zephyrus G14 setup
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or limitation you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative solutions or features you've considered

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - Power Management
        - GPU Management
        - ASUS Hardware Integration
        - Display Configuration
        - System Configuration
        - Documentation
        - Testing/Validation
        - User Interface/Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - Critical (blocking current usage)
        - High (significantly improves experience)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Compatibility
      description: What hardware would this feature support or require?
      placeholder: |
        - Specific laptop models
        - CPU/GPU requirements
        - Hardware features needed

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas about how this could be implemented?
      placeholder: |
        Technical details, configuration changes, or implementation approaches
        (This is optional but helpful)

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help implement this feature
        - label: I would be willing to test this feature
        - label: I would be willing to help with documentation

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that would help understand or implement this feature